<a href="https://colab.research.google.com/github/Omkarrasale34/Dibeties/blob/main/ML_Diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()


Saving diabetes.csv to diabetes (2).csv


In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv('diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
df.shape

(768, 9)

In [ ]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [ ]:
df.size


6912

In [ ]:
df.columns=df.columns.str.strip().str.lower()

In [ ]:
# columns where 0 is not a valid medical value

invalid_zero_cols = ['glucose', 'bloodpressure', 'skinthickness', 'insulin', 'bmi']

#replace 0 with nan?
df[invalid_zero_cols] = df[invalid_zero_cols].replace(0, np.nan)

In [ ]:
df.isnull().sum()

pregnancies                   0
glucose                       5
bloodpressure                35
skinthickness               227
insulin                     374
bmi                          11
diabetespedigreefunction      0
age                           0
outcome                       0
dtype: int64

In [ ]:
(df==0).any()

pregnancies                  True
glucose                     False
bloodpressure               False
skinthickness               False
insulin                     False
bmi                         False
diabetespedigreefunction    False
age                         False
outcome                      True
dtype: bool

In [ ]:
# input missing values

for col in invalid_zero_cols:
  df[col].fillna(df[col].mean(), inplace=True)

/tmp/ipython-input-3801018534.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)


In [ ]:
# median represent: a typical patient not too high not too low not influenced by outliers

In [ ]:
#feature target separation

#feature
x=df.drop(columns='outcome')
#target
y=df['outcome']

In [ ]:
x.columns

Index(['pregnancies', 'glucose', 'bloodpressure', 'skinthickness', 'insulin',
       'bmi', 'diabetespedigreefunction', 'age'],
      dtype='object')

In [ ]:
y.name

'outcome'

In [ ]:
# train and test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


In [ ]:
x_train.shape,x_test.shape

((614, 8), (154, 8))

In [ ]:
y.value_counts(normalize=True)

outcome
0    0.651042
1    0.348958
Name: proportion, dtype: float64

In [ ]:
y_train.value_counts(normalize=True)

outcome
0    0.653094
1    0.346906
Name: proportion, dtype: float64

In [ ]:
y_test.value_counts(normalize=True)

outcome
0    0.642857
1    0.357143
Name: proportion, dtype: float64

In [ ]:
# feature scaling - preporcessing

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [ ]:
#  here using logistic regression classifire because it is a
#  binary classification problem, strong baseline for medical data

from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(x_train_scaled, y_train)

# here now the model trained, using scaled feature , can implement sadty

LogisticRegression()

In [ ]:
# predictions
y_pred =log_reg.predict(x_test_scaled)

In [ ]:
y_pred[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1])

In [ ]:
log_reg.score(x_test_scaled, y_test)
# accuracy of test

0.7532467532467533

In [ ]:
log_reg.score(x_train_scaled, y_train)
# accuracy of train

0.7719869706840391

In [ ]:
y_prob = log_reg.predict_proba(x_test_scaled)
y_prob[:10]

array([[0.71728313, 0.28271687],
       [0.83606362, 0.16393638],
       [0.89460661, 0.10539339],
       [0.84634265, 0.15365735],
       [0.54099098, 0.45900902],
       [0.55368795, 0.44631205],
       [0.98575091, 0.01424909],
       [0.62421038, 0.37578962],
       [0.42665813, 0.57334187],
       [0.24360418, 0.75639582]])

In [ ]:
y_prob_diabetic=y_prob[:,1]
y_prob_diabetic[:10]

array([0.28271687, 0.16393638, 0.10539339, 0.15365735, 0.45900902,
       0.44631205, 0.01424909, 0.37578962, 0.57334187, 0.75639582])

In [ ]:
# confusion matrix

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred)
cm

# [TN FP]
# [FN TP]

# TN - true negative - actully non diabetic
# FP - false positive - actully non diabetic but predicted diabetic
# FN - false negative - actully diabetic but predicted non diabetic
# TP - true positive - actully diabetic

array([[82, 17],
       [21, 34]])

In [ ]:
# classification report

from sklearn.metrics import classification_report
cr=classification_report(y_test, y_pred)
print(cr)

# here will see about precision , recall , f1-score , support
# precision : how correct the model was when it said 0 or 1
# recall: how many real 0 and 1 it found
# f1-score: balance score of precision and recall
# support: how many actual  0 and 1 patients

# exampl for weighted average:
# The weighted average in a classification report is an overall metric (for precision, recall, and f1-score)
# that takes into account the number of true instances for each class (the 'support').


              precision    recall  f1-score   support

           0       0.80      0.83      0.81        99
           1       0.67      0.62      0.64        55

    accuracy                           0.75       154
   macro avg       0.73      0.72      0.73       154
weighted avg       0.75      0.75      0.75       154



In [ ]:
# next model we using here is SVM Suppport Vector Machine
# it finds atrong , margin used decision boundary than often improves recall on samll well scaled datasets

#the main reason to use is dataset is small in size ,we did the scalling chances are high to get better
#recall

In [ ]:
from sklearn.svm import SVC
svm_model = SVC(kernel ='linear',probability=True)
svm_model.fit(x_train_scaled,y_train)

SVC(kernel='linear', probability=True)

In [ ]:
y_pred_svm=svm_model.predict(x_test_scaled)

#evaluating
svm_model.score(x_test_scaled,y_test)

0.7532467532467533

In [ ]:
y_prob_svm =svm_model.predict_proba(x_test_scaled)
y_prob_svm[:10]

array([[0.71182119, 0.28817881],
       [0.82016072, 0.17983928],
       [0.88145222, 0.11854778],
       [0.83572589, 0.16427411],
       [0.52425314, 0.47574686],
       [0.54007575, 0.45992425],
       [0.98021005, 0.01978995],
       [0.64039241, 0.35960759],
       [0.44142516, 0.55857484],
       [0.25543468, 0.74456532]])

In [ ]:
#confusion matrix

from sklearn.metrics import confusion_matrix,classification_report
cm_svm=confusion_matrix(y_test, y_pred_svm)
cm

array([[82, 17],
       [21, 34]])

In [ ]:
# classification report

print (classification_report(y_test, y_pred_svm))


              precision    recall  f1-score   support

           0       0.80      0.83      0.81        99
           1       0.67      0.62      0.64        55

    accuracy                           0.75       154
   macro avg       0.73      0.72      0.73       154
weighted avg       0.75      0.75      0.75       154



In [ ]:
# ROC AUC Receiver Operating Characteristic Area Under the Curve


from sklearn.metrics import roc_auc_score
roc_auc_lr=roc_auc_score(y_test,y_prob[:,1])
roc_auc_svm=roc_auc_score(y_test,y_prob_svm[:,1])
print(roc_auc_lr)
print(roc_auc_svm)

# 81 for both lr n svm
# roc implies that both LR and SVM  correctly ranks a diabetic hogher than a non diebetic
# 82% ogf the time slides the threshould from 0-1, computes recall and false positive at each step, plots the curve

0.8242424242424242
0.8249770431588613
